apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: todo-ui
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: todos-app
spec:
  build:
    env:
    - name: BP_NODE_RUN_SCRIPTS
      value: build
    - name: BP_WEB_SERVER
      value: httpd
    - name: BP_WEB_SERVER_ROOT
      value: dist
    - name: BP_WEB_SERVER_ENABLE_PUSH_STATE
      value: "true"
  params:
  - name: clusterBuilder
    value: builder-for-web-servers
  source:
    git:
      url: https://github.com/odedia/todo-ui
      ref:
        branch: main
